site_name: ThinkThread SDK Documentation
site_description: Documentation for the Chain-of-Recursive-Thoughts SDK
site_author: Tomas Cupr

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - admonition

nav:
  - Home: index.md
  - Usage Guide: usage_guide.md
  - Developer Guide: developer_guide.md
  - Configuration Reference: configuration_reference.md
  - CLI Reference: cli_reference.md
